# Generated by Django 4.1.5 on 2023-03-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpresa', '0002_rename_place_id_employee_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary_id',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='location_id',
            new_name='location',
        ),
    ]
